"""Evidence-gated change-request delivery for completed Issue Campaigns."""

from __future__ import annotations

import asyncio
from collections.abc import Callable

from .change_request_delivery import (
    ChangeRequest,
    ChangeRequestProvider,
    ChangeRequestResult,
    EvidenceGatedDelivery,
)
from .contracts import ResearchArtifactContract
from .episode_package import EpisodePackage
from .issue_campaign import CampaignCandidate
from .step_repository import ResearchArtifactRepository


class CampaignChangeRequestDeliverer:
    def __init__(
        self,
        provider: ChangeRequestProvider,
        *,
        base_branch: str,
        head_branch: str | Callable[[EpisodePackage, CampaignCandidate], str],
        draft: bool = True,
    ) -> None:
        if not base_branch.strip():
            raise ValueError("base_branch is required")
        self.provider = provider
        self.base_branch = base_branch
        self.head_branch = head_branch
        self.draft = draft

    async def deliver(
        self,
        episode: EpisodePackage,
        candidate: CampaignCandidate,
        artifacts: tuple[ResearchArtifactContract, ...],
    ) -> ChangeRequestResult:
        repository = ResearchArtifactRepository()
        for artifact in artifacts:
            repository.add(artifact)
        delivery = EvidenceGatedDelivery(repository, self.provider)
        request = ChangeRequest(
            repository=episode.repository,
            base_branch=self.base_branch,
            head_branch=self._resolve_head(episode, candidate),
            title=self._title(episode),
            body=self._body(episode, candidate, artifacts),
            draft=self.draft,
        )
        return await asyncio.to_thread(
            delivery.create_for_run,
            episode.run_id,
            request,
        )

    def _resolve_head(
        self,
        episode: EpisodePackage,
        candidate: CampaignCandidate,
    ) -> str:
        if callable(self.head_branch):
            value = self.head_branch(episode, candidate)
        else:
            value = self.head_branch
        if not value.strip():
            raise ValueError("head_branch resolver returned an empty branch")
        return value

    @staticmethod
    def _title(episode: EpisodePackage) -> str:
        prefix = {
            "bug_fix": "fix",
            "feature": "feat",
            "refactor": "refactor",
            "performance": "perf",
            "research": "research",
        }.get(episode.task_type, "change")
        issue = f" issue #{episode.issue_number}" if episode.issue_number else ""
        return f"{prefix}: {episode.goal}{issue}"[:240]

    @staticmethod
    def _body(
        episode: EpisodePackage,
        candidate: CampaignCandidate,
        artifacts: tuple[ResearchArtifactContract, ...],
    ) -> str:
        criteria = "\n".join(
            f"- [x] {criterion}"
            for criterion in episode.acceptance_criteria
        )
        evidence = "\n".join(
            "| {type} | {step} | {verified} | `{digest}` |".format(
                type=artifact.artifact_type.value,
                step=artifact.step_id,
                verified="yes" if artifact.verified else "no",
                digest=artifact.content_hash[:12],
            )
            for artifact in sorted(
                artifacts,
                key=lambda item: (
                    item.artifact_type.value,
                    item.step_id,
                    item.artifact_id,
                ),
            )
        )
        changed_paths = sorted(
            {
                str(path)
                for artifact in artifacts
                for path in (
                    artifact.metadata.get("changed_paths", ())
                    if isinstance(
                        artifact.metadata.get("changed_paths", ()),
                        (list, tuple),
                    )
                    else ()
                )
            }
        )
        paths = "\n".join(f"- `{path}`" for path in changed_paths) or "- none"
        issue_line = (
            f"Closes #{episode.issue_number}"
            if episode.issue_number is not None
            else "No linked issue."
        )
        return f"""## AutoResearch delivery

{issue_line}

### Episode

- Episode: `{episode.episode_id}`
- Episode digest: `{episode.digest()}`
- Base revision: `{episode.base_revision}`
- Candidate: `{candidate.checkpoint.candidate_id}`
- Candidate revision: `{candidate.checkpoint.tree_revision}`
- Risk score: `{candidate.checkpoint.risk_score:.3f}`

### Acceptance criteria

{criteria}

### Changed paths

{paths}

### Verified evidence

| Artifact | Step | Verified | SHA-256 |
|---|---|---:|---|
{evidence}

> Generated by AutoResearch. Automatic merge remains disabled.
"""
